version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.13.0-rc.4-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq

networks:
  rabbitmq:
    driver: bridge 
   